# Generated by Django 3.0.2 on 2020-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0002_remove_travelguide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='temperature',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination',
            field=models.CharField(choices=[('Pakistan', 'Pakistan'), ('International', 'International')], default='Pakistan', max_length=20),
            preserve_default=False,
        ),
    ]
