# Generated by Django 3.0.2 on 2020-01-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0003_auto_20200122_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='NIC',
        ),
    ]
