# Generated by Django 3.0.2 on 2020-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0004_remove_client_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default=2, upload_to='images/packages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='images/destinations'),
        ),
    ]
