# Generated by Django 3.0.2 on 2020-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0005_auto_20200123_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(height_field=299, upload_to='images/comments', width_field=300)),
                ('comment', models.TextField()),
            ],
        ),
    ]
