# Generated by Django 3.0.2 on 2020-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, height_field=299, upload_to='images/comments', width_field=300),
        ),
    ]
