# Generated by Django 3.0.2 on 2020-01-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0007_auto_20200129_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/comments'),
        ),
    ]
