# Generated by Django 3.0.2 on 2020-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0008_auto_20200129_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/g1.jpg', upload_to='images/blog'),
            preserve_default=False,
        ),
    ]
