# Generated by Django 3.0.2 on 2020-02-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STPApp', '0010_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='fdsf', upload_to='images/members'),
            preserve_default=False,
        ),
    ]
